### ISSUE TITLE
why these services pending?

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#1]
hey guy,
  after helm install --name sitewhere ./sitewhere on a  4 nodes k8s(master,node1,node2,node3);
I run 'kubectl get svc --namespace default sitewhere-web-rest-http -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'' as the instruction, but got nothing ;

and when I run 'kubectl get svcs ' ,  found that “sitewhere-zoonav”&“sitewhere-web-rest-http”&“sitewhere-mosquitto-svc” these three svcs  were 'pending'，and I cannot connect sitewhere with the client ;
can anyone help me  please? Thanks a lot !

by the way:
My  images tag is not 2.0.0 , I changed it to 2.0.rc2 in the values.yaml file.

**Comment by GanKanTechnology** [comment]
And container logs as follows:
1、container 'sitewhere-zookeeper'  in pod 'sitewhere-zookeeper-0':
 2018-12-03 09:57:36,528 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x167737f39920000 type:create cxid:0x937 zxid:0x111 txntype:-1 reqpath:n/a Error Path:/brokers/topics/sitewhere.sitewhere1.global.tenant-model-updates/partitions/0 Error:KeeperErrorCode = NoNode for /brokers/topics/sitewhere.sitewhere1.global.tenant-model-updates/partitions/0
2018-12-03 09:57:36,563 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x167737f39920000 type:create cxid:0x938 zxid:0x112 txntype:-1 reqpath:n/a Error Path:/brokers/topics/sitewhere.sitewhere1.global.tenant-model-updates/partitions Error:KeeperErrorCode = NoNode for /brokers/topics/sitewhere.sitewhere1.global.tenant-model-updates/partitions
2018-12-03 09:57:48,715 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.244.1.125:44496
2018-12-03 09:57:48,739 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /10.244.1.125:44496 
------------------------------------------------------------------------
2、container 'sitewhere-web-rest'   in  pod 'sitewhere-web-rest-8669f7b6bc-srwnh '
 2018-12-03 10:10:18.514  INFO 1 --- [croservice Main] c.s.g.c.u.CachedUserManagementApiChannel : Waiting for GRPC service to become available. (status:TRANSIENT_FAILURE)
2018-12-03 10:10:18.614  INFO 1 --- [croservice Main] c.s.g.c.u.CachedUserManagementApiChannel : Waiting for GRPC service to become available. (status:TRANSIENT_FAILURE) 
-----------------------------------------------------------------------------------------------
mosquitto has no logs

**Comment by derekadams** [comment]
Currently, the `sitewhere-k8s` repository targets images provided by the `sitewhere-2.0.0` branch of the `sitewhere` project. We have not updated the Docker Hub images to include 2.0 because it hasn't been released, but you should be able to pull that branch and build it to your local repository. After that, the Helm chart should launch successfully and start the SiteWhere instance. We will be officially releasing SiteWhere 2.0 before the end of the month, so the images will be available on Docker Hub at that time. Thanks for your patience!

**Comment by GanKanTechnology** [comment]
Thanks a lot for your reply . I had built sitewhere service using docker-compose(version 1.18) on a standalone local CentOS-7.3 server  with sitewhere images 2.0.rc2 as  an example and it could run successfully. The client could communicate with the standalone sitewhere server using  'admin,password,http,192.168.1.21,8080'.  All the images needed were put in my docker registry '192.168.1.200:5000'. 
But when I tried to expand the sitewhere service  to k8s(GitVersion v1.11 build with kubeadm) using the same images above, I was blocked by that three 'pending' service after the helm installation. During the last week I didn't figure out why. Today  I'm still going to work  on it to check out why. Perhaps there's something  I may have omitted. Hope that you can give me more suggests about it. Thanks for your reply again.

**Comment by GanKanTechnology** [comment]
Some complement : I just notice that those three pending service have the same service type: LoadBalancer.  The other services are all "ClusterIP" type. I'm not on a cloud  platform. Maybe that's the reason?

**Comment by derekadams** [comment]
The images that worked on Docker Compose for RC2 no longer work on Kubernetes because we updated the service discovery process and added other environment features specific to k8s. If you want to run the k8s Helm chart, you will need to pull down the `sitewhere-2.0.0` branch from GitHub and run `gradle clean dockerImage` to build the Docker images locally. At that point, the Helm chart will correctly resolve the images and load successfully.

**Comment by GanKanTechnology** [comment]
Thanks for your reply. Thank you for your suggestion. I did as you said ，pulled down the sitewhere-2.0.0 branch ,  ran  ./gradle clean dockerImage， got the docker images locally，and  distributed them to the other nodes ,then helm installed it.  all  was still the three pending services. Sorry to say that I failed again.  I still think that the type of those three services  "LoadBalancer" ,may be the reason. It is known  that  the "LoadBalancer"depends on the cloud  platform, I guess that you develop this  based on some kind of cloud platform service  such as GKE(Google Kubernetes Engine).  So if I don't take any cloud platform service, can I  deploy the sitewhere successfully ? For now I'm thinking about two ways: 1.build something with some  tool to simulate a LoadBalancer
2. change the files, from 'LoadBalancer' to 'NodePort'
Maybe I'll try later. Hope your suggestions , Thank you !

**Comment by GanKanTechnology** [comment]
It  worked  when I change the template file , from 'LoadBalancer' to 'NodePort' , and add nodeport to them. Thank you for your work. I'll do something more  to test this sitewhere.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology, are you running a local or on-premise Kubernetes instalation? If so, it probably don't have a `LoadBalancer`. You may install one like [MetalLB](https://github.com/google/metallb) or change the `type` to `NodePort` of those services passing `--set services. web_rest. service. http.type=NodePort --set infra. zookeeper. zoonavigator. service. type=NodePort --set infra. mosquitto. service.type=NodePort`.

**Comment by GanKanTechnology** [comment]
Yes, it was running on a local k8s-cluster which has no LoadBalancer because I wanted to test it locally first. So I changed the type to NodePort as you said and it could run. Later, I will try to install MetalLB to do more test. Thank you all for your work about sitewhere. It seems a good IoT platform. You guys are doing great work, and wish you a great success Thank you !
