### ISSUE TITLE
Which apiVersion should I use?

### ISSUE THREAD

**Issue by javamonkey** [sitewhere/sitewhere-k8s#105]
i get error message when i run helm:
>helm install sitewhere

```
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"]
```
i check with command `helm template `, I do find some unsupported version ,sunch as 
`apiVersion: policy/v1beta1` in
sitewhere/charts/sitewhere-infra-core/charts/cp-zookeeper/templates/poddisruptionbudget.yaml

So, what solutions do we have?  k8s version is 1.16.2

**Comment by jorgevillaverde-sitewhere** [comment]
Can you provide this infromation:

**Provide Information**
Output of `helm version`:

Output of `kubectl version`:

Output of `helm ls sitewhere`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

SiteWhere App Version:

SiteWhere Chart Version:

Thanks

**Comment by javamonkey** [comment]
SiteWhere:2.1 
helm: 2.16 
kubectl:v1.16.0
minikube:v1.5.0
os:centos7

>>helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}



> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/386"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

> helm ls sitewhere
<empty>

>helm list
NAME        	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
mangy-gopher	1       	Sun Nov 10 08:01:33 2019	DEPLOYED	mysql-1.4.0	5.7.27     	default

> helm install --name sitewhere sitewhere/sitewhere
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"]

**Comment by jorgevillaverde-sitewhere** [comment]
What version of `sitewhere-k8s` are you using?
We have fix that issue in this issue #97, which was included in `sitewhere-k8s-0.2.5`.

**Comment by javamonkey** [comment]
I got same issue on branch  sitewhere-k8s-0.2.5. Sitewhere depend mongodb chart，influxdb chart。 I thought there is something wrong with these chart:

run "helm template ./sitewhere", the output contain many keyword "v1beta1",such as 

# Source:sitewhere/charts/sitewhere-infra-database/charts/influxdb/templates/deployment.yaml
apiVersion: extensions/v1beta1

# Source: sitewhere/charts/sitewhere-infra-core/charts/cp-kafka/templates/statefulset.yaml
apiVersion: apps/v1beta1

**Comment by jorgevillaverde-sitewhere** [comment]
ok, let me take a look at it. It seems that some of our dependencies are still using `v1beta1` apiVersion.
A temporal walkaround could be starting `minikube` with an older version of kubernetes.

```
minikube start --kubernetes-version v1.15.0
``` 

I'll get back to you a solution using Kuberntes v1.16

**Comment by javamonkey** [comment]
Thanks,I delpoyed stiewhere successfully,But I got some error message:

># helm list
NAME      	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE   
istio-init	1       	Mon Nov 11 22:03:59 2019	DEPLOYED	istio-init-1.3.5	1.3.5      	istio-system
saucy-fish	1       	Mon Nov 11 22:09:12 2019	DEPLOYED	sitewhere-0.2.6 	2.1        	default  

>#kubectl get pods 
[root@localhost ~]# kubectl get pods 
NAME                                                        READY   STATUS                       RESTARTS   AGE
saucy-fish-cassandra-0                                      0/1     Running                      2          22m
saucy-fish-cp-kafka-0                                       1/1     Running                      0          22m
saucy-fish-cp-kafka-1                                       1/1     Running                      0          22m
saucy-fish-cp-kafka-2                                       1/1     Running                      1          22m
saucy-fish-cp-zookeeper-0                                   1/1     Running                      0          22m
saucy-fish-cp-zookeeper-1                                   1/1     Running                      0          22m
saucy-fish-cp-zookeeper-2                                   1/1     Running                      0          22m
saucy-fish-influxdb-85b7c9799b-s795k                        1/1     Running                      1          22m
saucy-fish-mongodb-arbiter-0                                1/1     Running                      1          22m
saucy-fish-mongodb-primary-0                                0/1     Running                      0          22m
saucy-fish-mongodb-secondary-0                              0/1     Running                      0          22m
saucy-fish-postgresql-0                                     0/1     Pending                      0          22m
saucy-fish-sitewhere-asset-management-68ddc7849b-lrx5z      0/1     ContainerCreating            0          22m
saucy-fish-sitewhere-batch-operations-5d7df4fbd8-jfsbs      0/1     ContainerCreating            0          22m
saucy-fish-sitewhere-command-delivery-64d78d94cf-fzhkq      0/1     CreateContainerConfigError   0          22m
saucy-fish-sitewhere-device-management-5648758594-cr7jx     0/1     CreateContainerConfigError   0          22m
saucy-fish-sitewhere-device-registration-6bd6646db5-phb8j   0/1     CreateContainerConfigError   0          22m


>#kubectl describe pod saucy-fish-sitewhere-device-state-68f7995b8d-7w4b8

Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  30m                     default-scheduler  Successfully assigned default/saucy-fish-sitewhere-device-state-68f7995b8d-7w4b8 to minikube
  Normal   Pulling    29m                     kubelet, minikube  Pulling image "docker.io/sitewhere/service-device-state:latest"
  Normal   Pulled     26m                     kubelet, minikube  Successfully pulled image "docker.io/sitewhere/service-device-state:latest"
  Normal   Pulled     23m (x11 over 26m)      kubelet, minikube  Container image "docker.io/sitewhere/service-device-state:latest" already present on machine
  Warning  Failed     19m (x30 over 26m)      kubelet, minikube  Error: secret "sitewhere-tenantsdb" not found
  Normal   Pulled     15m (x13 over 17m)      kubelet, minikube  Container image "docker.io/sitewhere/service-device-state:latest" already present on machine



==================

all sitewhere service can not deployed beacuse of  "Error: secret "sitewhere-tenantsdb" not found"

**Comment by huangweiboy2** [comment]
@javamonkey So how to install k8s 1.16，Please！

**Comment by Sanstones** [comment]
I also get this question I need help

**Comment by Sanstones** [comment]
Error: validation failed: [unable to recognize "": no matches for kind "Gateway" in version "network

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @Sanstones,  
The error you are reporting is because Istio is not installed.
We are deploying a `Gateway` and a `VirtualService` as part of SiteWhere [Web Rest](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere/templates/Web-Rest.yaml#L117) microservice to form a Service Mesh using Istio.
Please, install Istio before installing SiteWhere.
By the way, we are working a supporting Kuberntes v1.16 as part of SiteWhere 3.0.
Regards

**Comment by Sanstones** [comment]
> Hi @Sanstones,
> The error you are reporting is because Istio is not installed.
> We are deploying a `Gateway` and a `VirtualService` as part of SiteWhere [Web Rest](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere/templates/Web-Rest.yaml#L117) microservice to form a Service Mesh using Istio.
> Please, install Istio before installing SiteWhere.
> By the way, we are working a supporting Kuberntes v1.16 as part of SiteWhere 3.0.
> Regards

Hi I think installed success when i got 
![image](https://user-images.githubusercontent.com/21982691/76813923-64fb4b80-6834-11ea-85d3-ebfeb38782ce.png)
but I can't login success, SiteWhere Admin.app No response，so I use chmore input http://localhost:80 show  no healthy upstream 
How can I solve this problem

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @Sanstones,
Have you seen all pods up and running?
Can you provide the output of the following command?
```kubectl get pod```
