### ISSUE TITLE
Failed to install sitewhere with helm

### ISSUE THREAD

**Issue by cecilwei** [sitewhere/sitewhere-k8s#128]
**Describe the bug**
I was trying to install sitewhere using helm chart by following the instruction in [https://sitewhere.io/docs/2.1.0/deployment/#install-sitewhere-from-sitewhere-helm-repository](url)

But I am getting the following error:
`Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"]
`

**Provide Information**
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`
Output of `helm ls sitewhere`
`Empty`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`I was installing on CentOS 7.7 on Azure VM`

SiteWhere App Version:

SiteWhere Chart Version:
Not sure

**To Reproduce**

1.    minikube start
2.   kubectl get namespace -L istio-injection
3.   kubectl label namespace default istio-injection=enabled
4.   helm repo add sitewhere https://sitewhere.io/helm-charts
5.   helm repo update
6.   helm install sitewhere sitewhere/sitewhere

**Expected behavior**
Sitewhere shall be installed without issues.

**Additional context**

**Comment by derekadams** [comment]
This may be due to our charts using beta interfaces that have been moved to stable in the latest versions of Kubernetes. We will go back and review the charts and update to reference the stable APIs.

**Comment by jorgevillaverde-sitewhere** [comment]
We'll upgrade our dependencies to support https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
