### ISSUE TITLE
The login problem

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere-k8s#134]
Hello, is there any time limit for users to log in JWT in your system? I deployed the system on k8s, I can log in at the beginning, but I can't log in a few days later. I don't know why, what is the log

![image](https://user-images.githubusercontent.com/63097736/80453772-808d6200-895b-11ea-8d4a-700946c804ae.png)

**Comment by jorgevillaverde-sitewhere** [comment]
Fixed by https://github.com/sitewhere/sitewhere/pull/816/commits/8ef46e981dcdd92361dea8d14081db259c28cb0f
