### ISSUE TITLE
Error: found in requirements.yaml, but missing in charts/ directory: sitewhere-infra-core, sitewhere-infra-database

### ISSUE THREAD

**Issue by alanliu95** [sitewhere/sitewhere-k8s#19]
**Describe the bug**
use git command to clone this repo, use cd comond into sitewhere-k8s/charts subdirectory. Then type `helm install --name sitewhere ./sitewhere`.Get th error info below.

> **Error: found in requirements.yaml, but missing in charts/ directory: sitewhere-infra-core, sitewhere-infra-database**

**Provide Information**
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

Output of `helm ls sitewhere`
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm
SiteWhere App Version:

SiteWhere Chart Version:

**To Reproduce**

**Expected behavior**
How to resolve this error for installing sitewhere 2.0
**Additional context**

**Comment by GanKanTechnology** [comment]
You need to update the helm repo:

helm repo add sitewhere https://sitewhere.io/helm-charts
helm repo update
helm repo list

**Comment by derekadams** [comment]
Also you may need to pull the content into a local `charts` directory with:
```
helm dependency update
```
We will update the documentation to prevent confusion in the future.

**Comment by alanliu95** [comment]
thanks much.
