### ISSUE TITLE
Question:  How to assign more storage to mongodb and kafka please?

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#27]
Hi @jorgevillaverde-sitewhere 
As the topic, if I want to assign 100Gi for mongodb and 100Gi for Kafka, ｗhich file should I adjust please?

In the latest branch "master", I found two tar files named "`sitewhere-infra-core-0.1.3.tgz`" and "`sitewhere-infra-database-0.1.5.tgz`"  in `sitewhere-k8s/charts/sitewhere/charts` .

Should I untar them and modify the` {mongodb.persistence.storage} `and` {mongodb.persistence.storage} `in those two "`value.yaml`" files？Is that the right way?

I tried  that and then tared them as the same name they were again. Then deploy the sitewhere with command  `helm install --name sitewhere ./sitewhere` .When I executed  "kubectl get pvc",  there was nothing different with before. Was I doing right or where did I do wrong please? The default storage value "10Gi" was not enough for large scale test.

Thank you.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology,

You have two ways of doing that:

1. Pass the values from the command line:

For example to assign `100Gi` to `mongo` and `100Gi` to `Kafka` you would execute:

```console
helm install --name sitewhere \
-- set sitewhere-infra-database.mongodb.persistence.storage=100Gi \
--set sitewhere-infra-core.kafka.persistence.storage=100Gi \
sitewhere/sitewhere
```

2. Create a custom `values.yaml`:

For example, copy `values.yaml` to `values-big-storage.yaml` and add/replace the following content:

```yaml
sitewhere-infra-core:
  kafka:
    persistence:
      storage: 100Gi
sitewhere-infra-database:
  mongodb:
    persistence:
      storage: 100Gi
```

Then, install SiteWhere using this file:

```console
helm install --name sitewhere \
-f values-big-storage.yaml \
sitewhere/sitewhere
```

*Note:* I'm only providing the 100Gi for mongo and Kafka, your `values.yaml` may have more configuration.

I hope this helps.

**Comment by GanKanTechnology** [comment]
Thanks a lot, that really helps. Have a good day~
