### ISSUE TITLE
Kafka's log grows up too rapidly.

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#29]
Hi guys~,
As the topic.
I've sent some data to the platform in a short time and found that the size of kafka log growing at a high speed.

When the storage of mongo reached about 0.3G, the size of kafka log had been reached nearly 1.3G（in each kafka pod）.

I think we can change the kafka log  cleaning strategy. Maybe we need to change the image  of kafka.
Just a suggestion.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology,

Thanks for the suggestion! Let us take a look about Kafka log cleaning strategy and we'll keep you posted.

**Comment by derekadams** [comment]
Hi @GanKanTechnology,

The default Kafka retention period is 7 days, so all of the data run through the topics that make up the SiteWhere pipeline is stored for that period. We can make the retention period configurable, but there are some advantages to having the data backed up in Kafka in addition to the database. It will allow you to re-run data from the topics in a case where data was processed incorrectly. The good news is that any data older than 7 days will be truncated, so there is a maximum upper boundary. However, in a large-scale smart city system, a retention period of 1 day may be a better fit. We'll look into making the retention period configurable.

**Comment by GanKanTechnology** [comment]
I think sooner or later we'll solve this ,so I closed this first.
