### ISSUE TITLE
Exception of the latest version (images 2.1.0 & sitewhere-k8s-0.2.0)

### ISSUE THREAD

**Issue by Warren-Z** [sitewhere/sitewhere-k8s#72]
Some info:
```
kubectl version: GitVersion:"v1.13.0",
helm version: v2.12.1
sitewhere-images version:2.1.0
helm list | grep sitewhere : 
sitewhere   1    Mon Jun 17 17:00:34 2019	DEPLOYED	sitewhere-0.2.0    	2.0    default  

```
As the topic, I deployed the latest version to see if there's some new fetures but got error as follow:

> kubectl logs sitewhere-web-rest-76cd7d6c6b-5zz77  
.......
> 2019-06-17 09:18:40.593 ERROR 1 --- [   Service Main] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up
> 
> java.net.UnknownHostException: cp-zookeeper: Name does not resolve
> 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_212]
> 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_212]
> 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_212]
.........

I'd like to make sure that if there's something wrong.
Thanks .

p.s.

**My operation steps :** 
git clone -b sitewhere-k8s-0.2.0 https://github.com/sitewhere/sitewhere-k8s.git
cd ./sitewhere-k8s/charts
helm repo update && helm dependency update
docker pull sitewhere/xxxxx:2.1.0 
Manually change the image tag in values.yaml from "latest" to "2.1.0";
helm install --name sitewhere ./sitewhere

**Pods after deploying :** 
sitewhere-asset-management-86987d74dc-6gfj8      1/1     Running   0          20m
sitewhere-batch-operations-6cf8cf75bc-qx2wk      1/1     Running   0          20m
sitewhere-command-delivery-696f9757c6-9kh4r      1/1     Running   0          20m
sitewhere-cp-kafka-0                             1/1     Running   0          37m
sitewhere-cp-kafka-1                             1/1     Running   0          37m
sitewhere-cp-kafka-2                             1/1     Running   0          37m
sitewhere-cp-zookeeper-0                         1/1     Running   0          37m
sitewhere-cp-zookeeper-1                         1/1     Running   0          37m
sitewhere-cp-zookeeper-2                         1/1     Running   0          37m
sitewhere-device-management-5fbcbfb97c-swkzm     1/1     Running   0          20m
sitewhere-device-registration-67b6b8df46-pvt2j   1/1     Running   0          20m
sitewhere-device-state-78f964ff79-nlrjn          1/1     Running   0          20m
sitewhere-event-management-75d558d679-hfggk      1/1     Running   0          20m
sitewhere-event-search-5bd844b687-fpbz5          1/1     Running   0          20m
sitewhere-event-sources-5f9cbd54b-knqzj          1/1     Running   0          20m
sitewhere-inbound-processing-54fb7ccc6-8bdbh     1/1     Running   0          20m
sitewhere-instance-management-ff4786c84-cnhlh    1/1     Running   0          20m
sitewhere-label-generation-5c8bb8c475-458zh      1/1     Running   0          20m
sitewhere-mongodb-arbiter-0                      1/1     Running   0          37m
sitewhere-mongodb-primary-0                      1/1     Running   0          37m
sitewhere-mongodb-secondary-0                    1/1     Running   0          37m
sitewhere-mosquitto-5955df46d8-js9dw             1/1     Running   0          37m
sitewhere-outbound-connectors-9799c49d-l4c5s     1/1     Running   0          20m
sitewhere-postgresql-0                           1/1     Running   0          37m
sitewhere-rule-processing-584778df94-s2ltl       1/1     Running   0          20m
sitewhere-schedule-management-778f79975c-5jprs   1/1     Running   0          20m
sitewhere-streaming-media-79cc897845-qhdfk       1/1     Running   0          20m
sitewhere-syncope-9cc85d6c8-fm76k                1/1     Running   0          37m
sitewhere-syncope-console-84f8f44d96-49bv6       1/1     Running   0          37m
sitewhere-syncope-enduser-79f597ffbf-xx8g8       1/1     Running   0          37m
sitewhere-web-rest-76cd7d6c6b-5zz77              1/1     Running   0          20m

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @Warren-Z,

`SiteWhere 2.1` and `sitewhere-k8s-0.2.0` are not officially release yet, so we recommend using `SiteWhere 2.0` and `sitewhere-k8s-0.1.9`. Although if you want to try the new features of `2.1` you'll need to previously install Isitio `1.1.7`.

The error you are getting is probably related to `sitewhere` chart dependency of `sitewhere-infra-core` and `sitewhere-infra-database`. Those charts are not published yet. 
You can still package them vi `helm package` and place them on `sitewhere/charts`.

**Comment by Warren-Z** [comment]
> Hi @Warren-Z,
> 
> `SiteWhere 2.1` and `sitewhere-k8s-0.2.0` are not officially release yet, so we recommend using `SiteWhere 2.0` and `sitewhere-k8s-0.1.9`. Although if you want to try the new features of `2.1` you'll need to previously install Isitio `1.1.7`.
> 
> The error you are getting is probably related to `sitewhere` chart dependency of `sitewhere-infra-core` and `sitewhere-infra-database`. Those charts are not published yet.
> You can still package them vi `helm package` and place them on `sitewhere/charts`.

Hi @jorgevillaverde-sitewhere , got it , thank u~
