### ISSUE TITLE
 It seems there's something wrong with rook

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#9]
Hi guys~
sorry to disturb again an again， as the topic says: something's wrong with the rook.

First of all :  sitewhere-k8s（2.0.1）, rook , metallb（for LoadBalancer） ,
helm install --name sitewhere ./sitewhere
then all pvcs are pending , a few pods are running and  others "Init:CrashLoopBackOff" 
Four results of command as follows
----------1st. kubectl get pvc--------------------------------------------
NAME                                           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   
data-sitewhere-consul-server-0                 Pending                                      rook-ceph-block
sitewhere-kafka-pv-sitewhere-kafka-0           Pending                                      rook-ceph-block
sitewhere-mongodb-pv-sitewhere-mongodb-0       Pending                                      rook-ceph-block
sitewhere-zookeeper-pv-sitewhere-zookeeper-0   Pending                                      rook-ceph-block

----------2nd. kubectl get sc--------------------------------------------
NAME                        PROVISIONER         
rook-ceph-block (default)   ceph.rook.io/block  

----------3rd. kubectl get CephBlockPool --all-namespaces------------
NAMESPACE   NAME          AGE
rook-ceph   replicapool

-----4th.kubectl describe pvc data-sitewhere-consul-server-0---------
Name:          data-sitewhere-consul-server-0
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:        
Labels:        app=consul
               chart=consul-0.1.0
               component=server
               hasDNS=true
               release=sitewhere
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"d239400c-118f-11e9-95d8-0a580af4053f","leaseDurationSeconds":15,"acquireTime":"2019-01-06T08:50:23Z","renewTime":"2019-...
               volume.beta.kubernetes.io/storage-provisioner: ceph.rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
Normal: waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
Warning:Failed to provision volume with StorageClass "rook-ceph-block": Failed to create rook block image replicapool/pvc-1b31b9da-1190-11e9-a5ab-fa163e2c2105: failed to create image pvc-1b31b9da-1190-11e9-a5ab-fa163e2c2105 in pool replicapool of size 10737418240: Failed to complete '': exit status 2. rbd: error opening pool 'replicapool': (2) No such file or directory                

------------------------------------------------------------------------------------------------------------------
The 4th step : Warning that ‘no replicapool’,but the 3rd step : there do have the 'replicapool' ，do you have any ideas about that please ?

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology, can you provide the output of `kubectl describe CephBlockPool replicapool -n rook-ceph` to see if there's some wrong with the `replicapool`
Thanks

**Comment by GanKanTechnology** [comment]
kubectl describe CephBlockPool replicapool -n rook-ceph
Name:         replicapool
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephBlockPool
Metadata:
  Creation Timestamp:  2019-01-06T08:49:11Z
  Generation:          1
  Resource Version:    32165
  Self Link:           /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephblockpools/replicapool
  UID:                 efb27c53-118f-11e9-a5ab-fa163e2c2105
Spec:
  Replicated:
    Size:  1
Events:    <none>

**Comment by GanKanTechnology** [comment]
Hi~@Jorge Eduardo Villaverde
       I think it's rook's problem because there's no rook-ceph-osd-0-xxxxx，only rook-ceph-osd-prepared-xxxx . Though I still have no idea how to deal with it
------------------------------------------------------------------------------------
kubectl get pods --all-namespaces
rook-ceph-system   rook-ceph-agent-bqsww                 1/1     Running     0          3m34s
rook-ceph-system   rook-ceph-agent-d9xp5                 1/1     Running     0          3m34s
rook-ceph-system   rook-ceph-agent-qlsrs                 1/1     Running     0          3m34s
rook-ceph-system   rook-ceph-operator-7d756cb7c9-4d9fg   1/1     Running     0          3m35s
rook-ceph-system   rook-discover-44c6q                   1/1     Running     0          3m34s
rook-ceph-system   rook-discover-vkgj4                   1/1     Running     0          3m34s
rook-ceph-system   rook-discover-vtj4v                   1/1     Running     0          3m34s
rook-ceph          rook-ceph-mgr-a-579779457d-vv9mb      1/1     Running     0          2m7s
rook-ceph          rook-ceph-mon-a-d7b49cb6f-rv7g8       1/1     Running     0          2m31s
rook-ceph          rook-ceph-mon-b-75b788b889-lg4hk      1/1     Running     0          2m25s
rook-ceph          rook-ceph-mon-c-69b7594b9-6xg2f       1/1     Running     0          2m14s
rook-ceph          rook-ceph-osd-prepare-worker1-4f5gl   0/2     Completed   4          114s
rook-ceph          rook-ceph-osd-prepare-worker2-nnkx7   0/2     Completed   4          114s
rook-ceph          rook-ceph-osd-prepare-worker3-j6f8w   0/2     Completed   4          114s

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology,

Could you follow this [guide](https://github.com/rook/rook/blob/master/Documentation/advanced-configuration.md#log-collection) and provide the rook logs so that we have more information?

Thanks!

**Comment by GanKanTechnology** [comment]
Hi @jorge ,I‘’ve solved it a moment ago,  it's  the  storage file-system，ext3，made the rook can't create OSD. Thanks for your attention , Later I'll try to test sitewhere-k8s-2.0.2

**Comment by jorgevillaverde-sitewhere** [comment]
I'm glad to hear that.
Regards
